# 02 — Data Cleaning

## Mục tiêu
- Kiểm tra dữ liệu thô: missing values, kiểu dữ liệu, giá trị bất thường
- Chọn lọc các cột quan trọng, loại bỏ cột dư thừa (>90% missing)
- Chuyển đổi các cột text sang dạng numeric (diện tích, giá bán, số phòng ngủ)
- Chuẩn hóa giá trị categorical (giấy tờ pháp lý)
- Lưu dataset đã clean để sử dụng cho các bước tiếp theo

In [1]:
import pandas as pd
import numpy as np
import warnings

warnings.filterwarnings("ignore")

In [2]:
df = pd.read_csv("../data/processed/dataset_merged.csv")

In [3]:
df.shape

(8273, 24)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8273 entries, 0 to 8272
Data columns (total 24 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   tieu_de              7964 non-null   object
 1   gia_ban              7961 non-null   object
 2   don_gia              7961 non-null   object
 3   dien_tich            7961 non-null   object
 4   dia_chi              8273 non-null   object
 5   mo_ta                7961 non-null   object
 6   dien_thoai           3959 non-null   object
 7   loai_hinh            7961 non-null   object
 8   dien_tich_dat        7961 non-null   object
 9   dien_tich_su_dung    3754 non-null   object
 10  gia_m2               7961 non-null   object
 11  giay_to_phap_ly      7460 non-null   object
 12  so_phong_ngu         7961 non-null   object
 13  so_phong_ve_sinh     5977 non-null   object
 14  tong_so_tang         5501 non-null   float64
 15  tinh_trang_noi_that  4432 non-null   object
 16  huong_cua_chinh      1321 non-null   object
 17  dac_diem             5207 non-null   object
 18  chieu_ngang          6106 non-null   object
 19  chieu_dai            5970 non-null   object
 20  ma_can               25 non-null     object
 21  ten_phan_khu_lo      25 non-null     object
 22  bieu_do_gia          8273 non-null   object
 23  source               8273 non-null   object
dtypes: float64(1), object(23)
memory usage: 1.5+ MB

### Nhận xét

Dataset ban đầu có **8,273 dòng** và **24 cột**. Quan sát sơ bộ:
- Tất cả các cột đều ở dạng **object** (text) trừ  (float64)
- Nhiều cột bị thiếu dữ liệu nghiêm trọng:  (25/8273),  (25/8273),  (1321/8273)
- Các cột quan trọng (, , ) có ~7,961 giá trị → ~312 dòng null (~3.8%)

In [5]:
df.columns

Index(['tieu_de', 'gia_ban', 'don_gia', 'dien_tich', 'dia_chi', 'mo_ta',
       'dien_thoai', 'loai_hinh', 'dien_tich_dat', 'dien_tich_su_dung',
       'gia_m2', 'giay_to_phap_ly', 'so_phong_ngu', 'so_phong_ve_sinh',
       'tong_so_tang', 'tinh_trang_noi_that', 'huong_cua_chinh', 'dac_diem',
       'chieu_ngang', 'chieu_dai', 'ma_can', 'ten_phan_khu_lo', 'bieu_do_gia',
       'source'],
      dtype='object')

In [6]:
missing = df.isnull().sum().sort_values(ascending=False)
missing

ten_phan_khu_lo        8248
ma_can                 8248
huong_cua_chinh        6952
dien_tich_su_dung      4519
dien_thoai             4314
tinh_trang_noi_that    3841
dac_diem               3066
tong_so_tang           2772
chieu_dai              2303
so_phong_ve_sinh       2296
chieu_ngang            2167
giay_to_phap_ly         813
don_gia                 312
dien_tich               312
gia_ban                 312
loai_hinh               312
so_phong_ngu            312
gia_m2                  312
mo_ta                   312
dien_tich_dat           312
tieu_de                 309
dia_chi                   0
bieu_do_gia               0
source                    0
dtype: int64

In [7]:
missing_percent = (df.isnull().sum() / len(df) * 100).sort_values(ascending=False)
missing_percent

ten_phan_khu_lo        99.697812
ma_can                 99.697812
huong_cua_chinh        84.032395
dien_tich_su_dung      54.623474
dien_thoai             52.145534
tinh_trang_noi_that    46.428140
dac_diem               37.060317
tong_so_tang           33.506588
chieu_dai              27.837544
so_phong_ve_sinh       27.752931
chieu_ngang            26.193642
giay_to_phap_ly         9.827149
don_gia                 3.771304
dien_tich               3.771304
gia_ban                 3.771304
loai_hinh               3.771304
so_phong_ngu            3.771304
gia_m2                  3.771304
mo_ta                   3.771304
dien_tich_dat           3.771304
tieu_de                 3.735042
dia_chi                 0.000000
bieu_do_gia             0.000000
source                  0.000000
dtype: float64

### Nhận xét Missing Values
- **>99% missing**: `ma_can`, `ten_phan_khu_lo` → gần như không có dữ liệu, loại bỏ
- **>80% missing**: `huong_cua_chinh` (84%) → loại bỏ
- **>50% missing**: `dien_tich_su_dung` (54.6%), `dien_thoai` (52.1%) → loại bỏ
- **33-47% missing**: `tinh_trang_noi_that`, `dac_diem`, `tong_so_tang` → loại bỏ
- **~3.8% missing**: Các cột chính (`gia_ban`, `dien_tich`, `loai_hinh`,...) → xóa dòng null
- **0% missing**: `dia_chi`, `bieu_do_gia`, `source` → giữ nguyên

In [8]:
df[(~df['tong_so_tang'].isnull())][[
    "chieu_ngang",
    "chieu_dai",
    "dien_tich",
    "dien_tich_dat",
    "dien_tich_su_dung",
    "gia_m2",
    "don_gia",
    "gia_ban",
    "so_phong_ngu",
    "tong_so_tang",
    "so_phong_ve_sinh",
    "dac_diem",
    "tinh_trang_noi_that",
    "giay_to_phap_ly",
    "loai_hinh",
    "dia_chi",
    # "ten_phan_khu_lo",
    # "ma_can",
    # "huong_cua_chinh",
    # "dien_thoai",
    # "mo_ta",
    # "tieu_de",
    # "bieu_do_gia",
    # "source"
]].head(5)

,chieu_ngang,chieu_dai,dien_tich,dien_tich_dat,dien_tich_su_dung,gia_m2,don_gia,gia_ban,so_phong_ngu,tong_so_tang,so_phong_ve_sinh,dac_diem,tinh_trang_noi_that,giay_to_phap_ly,loai_hinh,dia_chi
0,4.5 m,8 m,36 m²,36 m²,NaN,"106,94 triệu/m²","106,94 triệu/m²","3,85 tỷ",2 phòng,2.0,2 phòng,Nhà nở hậu,Nội thất đầy đủ,Đã có sổ,"Nhà ngõ, hẻm","Đường Lê Quang Định, Phường 7, Quận Bình Thạnh..."
2,7 m,7.7 m,54 m²,54 m²,NaN,"133,33 triệu/m²","133,33 triệu/m²","7,2 tỷ",3 phòng,2.0,2 phòng,Hẻm xe hơi,Hoàn thiện cơ bản,Đã có sổ,"Nhà ngõ, hẻm","Đường Nơ Trang Long, Phường 13, Quận Bình Thạn..."
5,5.6 m,21 m,120 m²,120 m²,166 m²,"108,33 triệu/m²","108,33 triệu/m²",13 tỷ,5 phòng,2.0,3 phòng,NaN,NaN,Đã có sổ,"Nhà ngõ, hẻm","Đường Bạch Đằng, Phường 15, Quận Bình Thạnh, T..."
6,4.2 m,11.3 m,59.4 m²,59.4 m²,59.4 m²,"188,55 triệu/m²","188,55 triệu/m²","11,2 tỷ",4 phòng,3.0,4 phòng,Hẻm xe hơi,NaN,Đã có sổ,"Nhà ngõ, hẻm","Đường Nguyễn Xí, Phường 26, Quận Bình Thạnh, T..."
8,4 m,20 m,80 m²,80 m²,320 m²,"322,50 triệu/m²","322,50 triệu/m²","25,8 tỷ",9 phòng,5.0,5 phòng,NaN,Nội thất đầy đủ,Đã có sổ,"Nhà mặt phố, mặt tiền","89, Đường Nguyễn Văn Thương, Phường 25, Quận B..."

In [9]:
df[(df['gia_m2'] != df['don_gia']) & df['don_gia'].notnull()][[
    "chieu_ngang",
    "chieu_dai",
    "dien_tich",
    "dien_tich_dat",
    "dien_tich_su_dung",
    "gia_m2",
    "don_gia",
    "gia_ban",
    "so_phong_ngu",
    "tong_so_tang",
    "so_phong_ve_sinh",
    "dac_diem",
    "tinh_trang_noi_that",
    "giay_to_phap_ly",
    "loai_hinh",
    "dia_chi",
    # "ten_phan_khu_lo",
    # "ma_can",
    # "huong_cua_chinh",
    # "dien_thoai",
    # "mo_ta",
    # "tieu_de",
    # "bieu_do_gia",
    # "source"
]].head(5)

Empty DataFrame
Columns: [chieu_ngang, chieu_dai, dien_tich, dien_tich_dat, dien_tich_su_dung, gia_m2, don_gia, gia_ban, so_phong_ngu, tong_so_tang, so_phong_ve_sinh, dac_diem, tinh_trang_noi_that, giay_to_phap_ly, loai_hinh, dia_chi]
Index: []

In [10]:
df[(df['dien_tich'] != df['dien_tich_dat']) & df['dien_tich_dat'].notnull()][[
    "chieu_ngang",
    "chieu_dai",
    "dien_tich",
    "dien_tich_dat",
    "dien_tich_su_dung",
    "gia_m2",
    "don_gia",
    "gia_ban",
    "so_phong_ngu",
    "tong_so_tang",
    "so_phong_ve_sinh",
    "dac_diem",
    "tinh_trang_noi_that",
    "giay_to_phap_ly",
    "loai_hinh",
    "dia_chi",
    # "ten_phan_khu_lo",
    # "ma_can",
    # "huong_cua_chinh",
    # "dien_thoai",
    # "mo_ta",
    # "tieu_de",
    # "bieu_do_gia",
    # "source"
]].head(5)

Empty DataFrame
Columns: [chieu_ngang, chieu_dai, dien_tich, dien_tich_dat, dien_tich_su_dung, gia_m2, don_gia, gia_ban, so_phong_ngu, tong_so_tang, so_phong_ve_sinh, dac_diem, tinh_trang_noi_that, giay_to_phap_ly, loai_hinh, dia_chi]
Index: []

In [11]:
df[
    (df['dien_tich'].isnull())
    & (df['gia_ban'].isnull())
    & (df['loai_hinh'].isnull())
    & (df['so_phong_ngu'].isnull())
    & (df['gia_m2'].isnull())
    & (df['mo_ta'].isnull())
    # & (df['tieu_de'].isnull())
].count()

tieu_de                  3
gia_ban                  0
don_gia                  0
dien_tich                0
dia_chi                312
mo_ta                    0
dien_thoai               0
loai_hinh                0
dien_tich_dat            0
dien_tich_su_dung        0
gia_m2                   0
giay_to_phap_ly          0
so_phong_ngu             0
so_phong_ve_sinh         0
tong_so_tang             0
tinh_trang_noi_that      0
huong_cua_chinh          0
dac_diem                 0
chieu_ngang              0
chieu_dai                0
ma_can                   0
ten_phan_khu_lo          0
bieu_do_gia            312
source                 312
dtype: int64

## 1. Chọn lọc cột quan trọng

```plaintext
keep_cols = [
    # "ten_phan_khu_lo        99.697812", --> Thiếu nhiều quá
    # "ma_can                 99.697812", --> Thiếu nhiều quá
    # "huong_cua_chinh        84.032395", --> Thiếu nhiều quá
    # "dien_tich_su_dung      54.623474", --> Thiếu nhiều quá, không thể tính median hay mean được do không có căn cứ
    # "dien_thoai             52.145534", --> Không liên quan
    # "don_gia                 3.771304", --> Có gia_m2 rồi
    # "dien_tich_dat           3.771304", --> Có dien_tich rồi
    # "source                  0.000000", --> không liên quan
    "tinh_trang_noi_that    46.428140", # có thể fill là unknown
    # "chieu_dai              27.837544", --> Là thông số tính dien_tich, không thể fill na được
    # "dac_diem               37.060317", --> Có thể trích từ mo_ta
    # "chieu_ngang            26.193642", --> Là thông số tính dien_tich, không thể fill na được
    "tong_so_tang           33.506588", # na có thể fill là 1 hoặc 2, nhưng sẽ không chính xác, nên bỏ luôn cột này
    "so_phong_ve_sinh       27.752931", # na có thể fill là 1 hoặc 2, nhưng sẽ không chính xác, nên bỏ luôn cột này
    "giay_to_phap_ly         9.827149", # có thể fill là unknown
    "dien_tich               3.771304",
    "gia_ban                 3.771304",
    "loai_hinh               3.771304",
    "so_phong_ngu            3.771304",
    "gia_m2                  3.771304", # gia_2 có thể suy từ gia_ban / dien_tich
    "mo_ta                   3.771304",
    "tieu_de                 3.735042",
    "dia_chi                 0.000000",
    "bieu_do_gia             0.000000",
]
```

In [12]:
keep_cols = [
    "giay_to_phap_ly",
    "dien_tich",
    "gia_ban",
    "loai_hinh",
    "so_phong_ngu",
    "mo_ta",
    "tieu_de",
    "dia_chi",
    "bieu_do_gia",
]

#

In [13]:
df = df[keep_cols]

In [14]:
df.shape

(8273, 9)

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8273 entries, 0 to 8272
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   giay_to_phap_ly  7460 non-null   object
 1   dien_tich        7961 non-null   object
 2   gia_ban          7961 non-null   object
 3   loai_hinh        7961 non-null   object
 4   so_phong_ngu     7961 non-null   object
 5   mo_ta            7961 non-null   object
 6   tieu_de          7964 non-null   object
 7   dia_chi          8273 non-null   object
 8   bieu_do_gia      8273 non-null   object
dtypes: object(9)
memory usage: 581.8+ KB

In [16]:
df.head()

,giay_to_phap_ly,dien_tich,gia_ban,loai_hinh,so_phong_ngu,mo_ta,tieu_de,dia_chi,bieu_do_gia
0,Đã có sổ,36 m²,"3,85 tỷ","Nhà ngõ, hẻm",2 phòng,🍀VÂN KIỀU AN CƯ🍀\r\n\r\n🏡 Nhà Lê Quang Định P5...,🍀VÂN KIỀU AN CƯ🍀 40m2 - Hẻm Ô Tô - Gần mặt tiề...,"Đường Lê Quang Định, Phường 7, Quận Bình Thạnh...","[134.04, 125.8, 125.8, 125.8, 138.64, 138.64, ..."
1,NaN,62 m²,"9,79 tỷ","Nhà ngõ, hẻm",4 phòng,"CHỈ 9.XTY - NHÀ MỚI KENG,XE HƠI NGỦ NHÀ GIÁP B...","9.xty,Nhà Hẻm Xe Hơi,Xây Mới Khu VIP giáp Phạm...","Đường Phạm Văn Đồng, Phường 13, Quận Bình Thạn...","[133.33, 135.54, 130.95, 130.02, 130.02, 136.3..."
2,Đã có sổ,54 m²,"7,2 tỷ","Nhà ngõ, hẻm",3 phòng,XE HƠI NGỦ TRONG NHÀ- NGANG 7M - HIẾM - NƠ TRA...,XE HƠI NGỦ TRONG NHÀ- NGANG 7M - HIẾM - NƠ TRA...,"Đường Nơ Trang Long, Phường 13, Quận Bình Thạn...","[168.37, 168.37, 120.71, 120.71, 124.24, 124.5..."
3,Đã có sổ,83 m²,"8,5 tỷ","Nhà ngõ, hẻm",3 phòng,#e45\r\n🛎️ NHÀ LỚN HẺM ÔTÔ NGAY HÀNG XANH – TI...,🛎️ NHÀ LỚN HẺM ÔTÔ NGAY HÀNG XANH – TIỆN XÂY M...,"Đường Xô Viết Nghệ Tĩnh, Phường 21, Quận Bình ...","[159.22, 159.22, 157.45, 157.45, 135.08, 122.2..."
4,Đã có sổ,18 m²,"2,85 tỷ","Nhà ngõ, hẻm",2 phòng,Nhà hẻm cách đường mặt tiền 20m\r\nNhà ở khu v...,Nhà hẻm cách đường mặt tiền 20m,"Đường Chu Văn An, Phường 12, Quận Bình Thạnh, ...","[132.67, 132.67, 169.64, 169.64, 133.33, 133.3..."

## 2. Chuẩn hóa cột

In [17]:
df["giay_to_phap_ly"].unique()

array(['Đã có sổ', nan, 'Đang chờ sổ', 'Sổ chung / công chứng vi bằng',
       'Giấy tờ viết tay', 'Không có sổ'], dtype=object)

In [18]:
df["giay_to_phap_ly"] = df["giay_to_phap_ly"].str.lower()

In [19]:
df["giay_to_phap_ly"].head()

0    đã có sổ
1         NaN
2    đã có sổ
3    đã có sổ
4    đã có sổ
Name: giay_to_phap_ly, dtype: object

In [20]:
df.loc[df["giay_to_phap_ly"].isnull(), "giay_to_phap_ly"] = "chưa xác định"

In [21]:
df["giay_to_phap_ly"].isnull().sum()

np.int64(0)

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8273 entries, 0 to 8272
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   giay_to_phap_ly  8273 non-null   object
 1   dien_tich        7961 non-null   object
 2   gia_ban          7961 non-null   object
 3   loai_hinh        7961 non-null   object
 4   so_phong_ngu     7961 non-null   object
 5   mo_ta            7961 non-null   object
 6   tieu_de          7964 non-null   object
 7   dia_chi          8273 non-null   object
 8   bieu_do_gia      8273 non-null   object
dtypes: object(9)
memory usage: 581.8+ KB

In [23]:
df = df[
    ~(
        (df['dien_tich'].isnull())
        & (df['gia_ban'].isnull())
        & (df['loai_hinh'].isnull())
        & (df['so_phong_ngu'].isnull())
        & (df['mo_ta'].isnull())
    )
]

In [24]:
df.shape

(7961, 9)

### Nhận xét
Sau khi xóa 312 dòng thiếu thông tin chính, dataset còn **7,961 dòng** với **9 cột** đã chọn.

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7961 entries, 0 to 8272
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   giay_to_phap_ly  7961 non-null   object
 1   dien_tich        7961 non-null   object
 2   gia_ban          7961 non-null   object
 3   loai_hinh        7961 non-null   object
 4   so_phong_ngu     7961 non-null   object
 5   mo_ta            7961 non-null   object
 6   tieu_de          7961 non-null   object
 7   dia_chi          7961 non-null   object
 8   bieu_do_gia      7961 non-null   object
dtypes: object(9)
memory usage: 622.0+ KB

## 3. Chuyển đổi cột  sang numeric

In [26]:
df['dien_tich'].unique()

array(['36 m²', '62 m²', '54 m²', '83 m²', '18 m²', '120 m²', '59.4 m²',
       '26 m²', '80 m²', '68 m²', '60 m²', '200 m²', '88 m²', '48 m²',
       '70 m²', '130 m²', '303 m²', '48.9 m²', '92 m²', '20 m²', '40 m²',
       '72 m²', '34 m²', '110 m²', '32 m²', '30 m²', '63.6 m²', '17 m²',
       '35 m²', '27 m²', '50 m²', '56 m²', '78 m²', '44 m²', '14 m²',
       '24 m²', '46 m²', '38.7 m²', '52 m²', '105 m²', '90 m²', '35.5 m²',
       '53 m²', '42.2 m²', '22 m²', '19 m²', '55 m²', '64 m²', '33 m²',
       '41.3 m²', '45 m²', '31 m²', '43 m²', '87 m²', '15 m²', '67 m²',
       '125 m²', '47 m²', '25 m²', '41 m²', '81 m²', '38.8 m²', '79 m²',
       '12.5 m²', '22.8 m²', '115 m²', '16.2 m²', '73.6 m²', '82 m²',
       '69 m²', '300 m²', '74 m²', '75 m²', '57 m²', '28 m²', '63 m²',
       '155 m²', '58 m²', '32.4 m²', '85 m²', '37 m²', '52.6 m²',
       '34.5 m²', '88.5 m²', '161 m²', '68.1 m²', '76 m²', '27.5 m²',
       '38.1 m²', '73 m²', '96 m²', '45.7 m²', '39 m²', '66 m²',
       '10.6 m²', '21 m²', '12 m²', '30.5 m²', '99 m²', '30.9 m²',
       '117 m²', '86 m²', '59 m²', '86.7 m²', '26.71 m²', '40.3 m²',
       '13 m²', '150 m²', '42 m²', '156 m²', '190 m²', '94 m²', '22.7 m²',
       '98 m²', '55.7 m²', '10 m²', '45.9 m²', '24.5 m²', '500 m²',
       '108 m²', '65 m²', '134 m²', '51 m²', '116 m²', '84 m²', '19.2 m²',
       '16 m²', '23 m²', '38 m²', '97 m²', '100 m²', '35.6 m²', '30.2 m²',
       '168 m²', '15.5 m²', '162 m²', '131.2 m²', '61 m²', '77 m²',
       '66.3 m²', '29 m²', '82.5 m²', '93 m²', '64.6 m²', '33.4 m²',
       '76.2 m²', '126 m²', '17.6 m²', '45.5 m²', '32.8 m²', '52.67 m²',
       '42.6 m²', '320 m²', '207 m²', '49 m²', '31.5 m²', '95 m²',
       '104 m²', '102 m²', '72.5 m²', '286 m²', '143 m²', '15.6 m²',
       '92.2 m²', '268 m²', '65.7 m²', '23.77 m²', '20.5 m²', '181 m²',
       '179 m²', '145 m²', '275 m²', '26.7 m²', '240 m²', '49.4 m²',
       '97.4 m²', '50.4 m²', '20.4 m²', '103 m²', '135 m²', '44.9 m²',
       '101 m²', '164 m²', '80.3 m²', '18.7 m²', '23.94 m²', '133.9 m²',
       '38.3 m²', '60.2 m²', '54.2 m²', '57.1 m²', '46.5 m²', '18.2 m²',
       '91.2 m²', '51.2 m²', '17.8 m²', '42.5 m²', '131 m²', '25.5 m²',
       '31.8 m²', '160 m²', '75.8 m²', '56.4 m²', '10.5 m²', '124.8 m²',
       '122.9 m²', '34.6 m²', '64.7 m²', '154 m²', '29.93 m²', '111 m²',
       '216 m²', '140 m²', '18.15 m²', '195 m²', '226 m²', '118 m²',
       '70.2 m²', '65.5 m²', '33.7 m²', '37.2 m²', '76.8 m²', '23.5 m²',
       '44.3 m²', '43.4 m²', '33.1 m²', '44.4 m²', '30.4 m²', '58.7 m²',
       '144.2 m²', '35.2 m²', '21.2 m²', '73.1 m²', '92.8 m²', '19.3 m²',
       '79.9 m²', '49.7 m²', '40.4 m²', '19.5 m²', '32.1 m²', '53.6 m²',
       '28.8 m²', '255 m²', '71 m²', '36.08 m²', '43.1 m²', '121.5 m²',
       '17.2 m²', '171 m²', '119 m²', '90.5 m²', '58.8 m²', '26.5 m²',
       '65.1 m²', '58.3 m²', '23.7 m²', '31.2 m²', '28.4 m²', '290 m²',
       '85.3 m²', '46.6 m²', '46.1 m²', '127 m²', '49.5 m²', '39.5 m²',
       '128 m²', '106 m²', '47.6 m²', '92.9 m²', '54.7 m²', '41.1 m²',
       '180 m²', '77.8 m²', '20.2 m²', '13.2 m²', '142.6 m²', '73.7 m²',
       '67.5 m²', '27.3 m²', '23.8 m²', '27.7 m²', '52.5 m²', '79.2 m²',
       '336 m²', '48.7 m²', '165 m²', '58.5 m²', '114 m²', '67.2 m²',
       '36.6 m²', '47.8 m²', '91 m²', '68.4 m²', '79.5 m²', '25.3 m²',
       '41.9 m²', '37.1 m²', '63.7 m²', '11 m²', '76.6 m²', '52.7 m²',
       '50.2 m²', '144 m²', '43.2 m²', '158 m²', '61.1 m²', '43.9 m²',
       '205 m²', '72.9 m²', '67.7 m²', '63.8 m²', '22.2 m²', '121 m²',
       '167 m²', '21.3 m²', '44.5 m²', '204 m²', '40.25 m²', '27.9 m²',
       '133 m²', '41.6 m²', '192 m²', '55.3 m²', '85.5 m²', '46.7 m²',
       '82.7 m²', '100.8 m²', '15.3 m²', '30.1 m²', '51.6 m²', '87.4 m²',
       '43.6 m²', '57.9 m²', '99.5 m²', '59.8 m²', '212.5 m²', '89 m²',
       '215 m²', '250 m²', '914.5 m²', '81.4 m²', '104.5 m²', '33.5 m²',
       '49.1 m²', '242 m²', '915 m²', '45.8 m²', '51.8 m²', '24.4 m²',
       '97.6 m²', '46.8 m²', '57.4 m²', '230 m²', '48.5 m²', '21.8 m²',
       '52.2 m²', '33.6 m²', '192.4 m²', '107 m²', '47.7 m²', '253 m²',
       '33.2 m²', '34.3 m²', '75.2 m²', '153 m²', '49.6 m²', '112 m²',
       '24.62 m²', '76.5 m²', '58.56 m²', '152 m²', '182.7 m²', '123 m²',
       '17.4 m²', '177 m²', '62.7 m²', '83.3 m²', '30.6 m²', '104.3 m²',
       '73.4 m²', '40.9 m²', '22.4 m²', '68.5 m²', '220 m²', '87.6 m²',
       '47.5 m²', '94.3 m²', '137 m²', '113 m²', '210 m²', '70.5 m²',
       '51.4 m²', '27.1 m²', '53.2 m²', '53.5 m²', '18.1 m²', '208 m²',
       '16.3 m²', '78.2 m²', '39.8 m²', '50.3 m²', '31.59 m²', '10.87 m²',
       '232 m²', '86.6 m²', '113.12 m²', '159 m²', '38.4 m²', '27.306 m²',
       '65.8 m²', '61.6 m²', '57.2 m²', '37.7 m²', '135.5 m²', '62.46 m²',
       '36.4 m²', '191 m²', '33.25 m²', '57.6 m²', '109 m²', '42.56 m²',
       '73.5 m²', '29.4 m²', '193 m²', '46.15 m²', '39.4 m²', '122 m²',
       '36.1 m²', '186 m²', '80.8 m²', '141 m²', '52.9 m²', '147 m²',
       '1400 m²', '34.2 m²', '36.2 m²', '185 m²', '45.3 m²', '93.4 m²',
       '73.15 m²', '58.6 m²', '61.2 m²', '600 m²', '37.9 m²', '55.476 m²',
       '218 m²', '25.272 m²', '99.4 m²', '50.5 m²', '51.7 m²', '289 m²',
       '62.5 m²', '80.1 m²', '49.2 m²', '174 m²', '219 m²', '101.6 m²',
       '39.2 m²', '36.9 m²', '25.7 m²', '56.6 m²', '21.56 m²', '48.4 m²',
       '18.6 m²', '50.7 m²', '41.8 m²', '53.7 m²', '64.4 m²', '77.9 m²',
       '56.2 m²', '80.4 m²', '30.3 m²', '62.2 m²', '111.5 m²', '26.4 m²',
       '59.3 m²', '41.85 m²', '34.16 m²', '53.9 m²', '176 m²', '61.4 m²',
       '46.2 m²', '38.5 m²', '14.5 m²', '182 m²', '136 m²', '37.5 m²',
       '68.3 m²', '76.1 m²', '59.2 m²', '14.85 m²', '54.8 m²', '400 m²',
       '30.94 m²', '21.4 m²', '53.3 m²', '170 m²', '86.9 m²', '42.9 m²',
       '28.69 m²', '154.8 m²', '71.5 m²', '55.4 m²', '212 m²', '86.72 m²',
       '20.76 m²', '25.8 m²', '57.3 m²', '54.6 m²', '142 m²', '346 m²',
       '79.75 m²', '60.6 m²', '31.9 m²', '22.5 m²', '39.6 m²', '50.6 m²',
       '49.9 m²', '29.25 m²', '84.4 m²', '24.75 m²', '430 m²', '93.5 m²',
       '62.3 m²', '61.5 m²', '75.6 m²', '373 m²', '276 m²', '85.6 m²',
       '39.1 m²', '74.1 m²', '37.8 m²', '58.41 m²', '297 m²', '22.05 m²',
       '66.2 m²', '27.4 m²', '56.5 m²', '37.3 m²', '16.5 m²', '40.5 m²',
       '28.5 m²', '17.5 m²', '64.2 m²', '60.7 m²', '52.8 m²', '92.5 m²',
       '95.5 m²', '223 m²', '64.9 m²', '42.77 m²', '175 m²', '13.1 m²',
       '27.6 m²', '71.4 m²', '82.8 m²', '16.8 m²', '77.5 m²', '148 m²',
       '36.7 m²', '70.4 m²', '36.8 m²', '43.5 m²', '77.6 m²', '25.6 m²',
       '132 m²', '115.7 m²', '14.6 m²', '201 m²', '51.3 m²', '104.8 m²',
       '51.5 m²', '225 m²', '146 m²', '17.9 m²', '32.7 m²', '21.7 m²',
       '107.1 m²', '234 m²', '39.7 m²', '65.468 m²', '62.4 m²',
       '80.688 m²', '50.16 m²', '168.88 m²', '31.3 m²', '49.8 m²',
       '58.2 m²', '54.9 m²', '87.5 m²', '23.4 m²', '148.9 m²', '22.6 m²',
       '299.85 m²', '252 m²', '59.1 m²', '68.9 m²', '45.6 m²', '51.9 m²',
       '166 m²', '10.4 m²', '66.4 m²', '48.6 m²', '151 m²', '36.3 m²',
       '63.1 m²', '47.9 m²', '83.7 m²', '68.8 m²', '54.5 m²', '150.3 m²',
       '61.7 m²', '92.4 m²', '93.6 m²', '64.8 m²', '157 m²', '88.9 m²',
       '101.02 m²', '58.4 m²', '51.1 m²', '226.2 m²', '723 m²', '178 m²',
       '41.2 m²', '159.2 m²', '138 m²', '53.4 m²', '52.3 m²', '149 m²',
       '61.3 m²', '18.9 m²', '35.4 m²', '20.1 m²', '69.2 m²', '47.3 m²',
       '27.55 m²', '28.1 m²', '25.2 m²', '12.3 m²', '139 m²', '41.4 m²',
       '18.4 m²', '180.6 m²', '31.7 m²', '72.2 m²', '11.3 m²', '57.35 m²',
       '67.1 m²', '32.6 m²', '116.4 m²', '67.6 m²'], dtype=object)

In [27]:
def transform_dien_tich(value):
    if pd.isnull(value):
        return value
    if isinstance(value, str):
        value = value.replace("m2", "").replace("m²", "").strip()
        try:
            return float(value)
        except ValueError:
            return np.nan
    return value

df['dien_tich'] = df['dien_tich'].apply(transform_dien_tich)

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7961 entries, 0 to 8272
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   giay_to_phap_ly  7961 non-null   object
 1   dien_tich        7961 non-null   float64
 2   gia_ban          7961 non-null   object
 3   loai_hinh        7961 non-null   object
 4   so_phong_ngu     7961 non-null   object
 5   mo_ta            7961 non-null   object
 6   tieu_de          7961 non-null   object
 7   dia_chi          7961 non-null   object
 8   bieu_do_gia      7961 non-null   object
dtypes: float64(1), object(8)
memory usage: 622.0+ KB

### Nhận xét
Cột  đã được chuyển từ dạng text (vd: "36 m²") sang **float64** thành công. Các bước xử lý:
- Loại bỏ ký tự "m2", "m²"
- Parse sang float
- Giá trị không parse được → NaN

In [29]:
df.head()

,giay_to_phap_ly,dien_tich,gia_ban,loai_hinh,so_phong_ngu,mo_ta,tieu_de,dia_chi,bieu_do_gia
0,đã có sổ,36.0,"3,85 tỷ","Nhà ngõ, hẻm",2 phòng,🍀VÂN KIỀU AN CƯ🍀\r\n\r\n🏡 Nhà Lê Quang Định P5...,🍀VÂN KIỀU AN CƯ🍀 40m2 - Hẻm Ô Tô - Gần mặt tiề...,"Đường Lê Quang Định, Phường 7, Quận Bình Thạnh...","[134.04, 125.8, 125.8, 125.8, 138.64, 138.64, ..."
1,chưa xác định,62.0,"9,79 tỷ","Nhà ngõ, hẻm",4 phòng,"CHỈ 9.XTY - NHÀ MỚI KENG,XE HƠI NGỦ NHÀ GIÁP B...","9.xty,Nhà Hẻm Xe Hơi,Xây Mới Khu VIP giáp Phạm...","Đường Phạm Văn Đồng, Phường 13, Quận Bình Thạn...","[133.33, 135.54, 130.95, 130.02, 130.02, 136.3..."
2,đã có sổ,54.0,"7,2 tỷ","Nhà ngõ, hẻm",3 phòng,XE HƠI NGỦ TRONG NHÀ- NGANG 7M - HIẾM - NƠ TRA...,XE HƠI NGỦ TRONG NHÀ- NGANG 7M - HIẾM - NƠ TRA...,"Đường Nơ Trang Long, Phường 13, Quận Bình Thạn...","[168.37, 168.37, 120.71, 120.71, 124.24, 124.5..."
3,đã có sổ,83.0,"8,5 tỷ","Nhà ngõ, hẻm",3 phòng,#e45\r\n🛎️ NHÀ LỚN HẺM ÔTÔ NGAY HÀNG XANH – TI...,🛎️ NHÀ LỚN HẺM ÔTÔ NGAY HÀNG XANH – TIỆN XÂY M...,"Đường Xô Viết Nghệ Tĩnh, Phường 21, Quận Bình ...","[159.22, 159.22, 157.45, 157.45, 135.08, 122.2..."
4,đã có sổ,18.0,"2,85 tỷ","Nhà ngõ, hẻm",2 phòng,Nhà hẻm cách đường mặt tiền 20m\r\nNhà ở khu v...,Nhà hẻm cách đường mặt tiền 20m,"Đường Chu Văn An, Phường 12, Quận Bình Thạnh, ...","[132.67, 132.67, 169.64, 169.64, 133.33, 133.3..."

## 4. Chuyển đổi cột  sang numeric

In [30]:
df["gia_ban"].unique()

array(['3,85 tỷ', '9,79 tỷ', '7,2 tỷ', '8,5 tỷ', '2,85 tỷ', '13 tỷ',
       '11,2 tỷ', '4,58 tỷ', '25,8 tỷ', '11,3 tỷ', '11,5 tỷ', '24,5 tỷ',
       '33,9 tỷ', '4,7 tỷ', '9,3 tỷ', '10,8 tỷ', '62 tỷ', '8 tỷ', '11 tỷ',
       '6,4 tỷ', '5,959 tỷ', '25,2 tỷ', '3,68 tỷ', '5,98 tỷ', '7 tỷ',
       '3,98 tỷ', '4,68 tỷ', '22 tỷ', '3,9 tỷ', '6,25 tỷ', '7,3 tỷ',
       '6,19 tỷ', '7,89 tỷ', '7,79 tỷ', '5,5 tỷ', '2,75 tỷ', '5,65 tỷ',
       '6,5 tỷ', '5 tỷ', '5,45 tỷ', '11,9 tỷ', '6,868 tỷ', '7,5 tỷ',
       '9,5 tỷ', '9,6 tỷ', '7,6 tỷ', '10,29 tỷ', '4 tỷ', '15 tỷ',
       '3,55 tỷ', '7,9 tỷ', '6,95 tỷ', '8,45 tỷ', '18 tỷ', '14,5 tỷ',
       '6,8 tỷ', '8,2 tỷ', '2,7 tỷ', '5,8 tỷ', '10,1 tỷ', '3,8 tỷ',
       '10 tỷ', '11,8 tỷ', '2,9 tỷ', '2,35 tỷ', '7,88 tỷ', '7,59 tỷ',
       '19,5 tỷ', '7,65 tỷ', '7,4 tỷ', '16 tỷ', '15,999 tỷ', '4,59 tỷ',
       '22,5 tỷ', '5,35 tỷ', '6 tỷ', '11,98 tỷ', '7,8 tỷ', '2,34 tỷ',
       '3,94 tỷ', '12 tỷ', '6,48 tỷ', '5,2 tỷ', '9,99 tỷ', '1,9 tỷ',
       '4,95 tỷ', '13,4 tỷ', '7,99 tỷ', '4,75 tỷ', '8,95 tỷ', '5,95 tỷ',
       '9,995 tỷ', '10,19 tỷ', '29,9 tỷ', '10,5 tỷ', '8,999 tỷ', '9,9 tỷ',
       '3,99 tỷ', '4,35 tỷ', '6,99 tỷ', '5,39 tỷ', '30 tỷ', '9,4 tỷ',
       '32,6 tỷ', '5,1 tỷ', '5,68 tỷ', '5,58 tỷ', '8,8 tỷ', '4,86 tỷ',
       '6,35 tỷ', '4,45 tỷ', '7,98 tỷ', '9,8 tỷ', '3,89 tỷ', '5,75 tỷ',
       '9,49 tỷ', '7,85 tỷ', '7,19 tỷ', '10,75 tỷ', '11,65 tỷ', '6,85 tỷ',
       '3,2 tỷ', '6,05 tỷ', '8,9 tỷ', '4,85 tỷ', '45 tỷ', '8,3 tỷ',
       '6,6 tỷ', '12,9 tỷ', '7,69 tỷ', '6,89 tỷ', '5,89 tỷ', '4,79 tỷ',
       '1,85 tỷ', '2,2 tỷ', '6,86 tỷ', '2,45 tỷ', '2,4 tỷ', '4,36 tỷ',
       '7,15 tỷ', '12,6 tỷ', '4,2 tỷ', '5,9 tỷ', '10,88 tỷ', '13,8 tỷ',
       '9,899 tỷ', '7,45 tỷ', '12,5 tỷ', '2,57 tỷ', '9,2 tỷ', '9,89 tỷ',
       '8,7 tỷ', '4,98 tỷ', '7,75 tỷ', '18,5 tỷ', '2,58 tỷ', '7,95 tỷ',
       '16,8 tỷ', '13,5 tỷ', '3,65 tỷ', '14,8 tỷ', '13,57 tỷ', '15,5 tỷ',
       '26 tỷ', '3,69 tỷ', '5,99 tỷ', '6,39 tỷ', '3,05 tỷ', '1,75 tỷ',
       '15,9 tỷ', '8,79 tỷ', '5,49 tỷ', '5,999 tỷ', '5,19 tỷ', '6,69 tỷ',
       '535 tỷ', '2,39 tỷ', '9,95 tỷ', '6,65 tỷ', '2,55 tỷ', '5,85 tỷ',
       '10,28 tỷ', '13,9 tỷ', '12,599 tỷ', '7,25 tỷ', '16,5 tỷ', '4,8 tỷ',
       '10,99 tỷ', '3,95 tỷ', '2,25 tỷ', '16,9 tỷ', '23 tỷ', '4,38 tỷ',
       '4,5 tỷ', '29 tỷ', '10,2 tỷ', '7,7 tỷ', '3,7 tỷ', '8,4 tỷ',
       '3,999 tỷ', '8,89 tỷ', '2,89 tỷ', '6,49 tỷ', '20 tỷ', '2,95 tỷ',
       '39 tỷ', '11,6 tỷ', '25 tỷ', '7,84 tỷ', '5,88 tỷ', '4,55 tỷ',
       '3,35 tỷ', '21,9 tỷ', '6,2 tỷ', '5,7 tỷ', '5,79 tỷ', '12,8 tỷ',
       '6,9 tỷ', '8,75 tỷ', '14 tỷ', '10,9 tỷ', '13,6 tỷ', '5,78 tỷ',
       '12,49 tỷ', '10,279 tỷ', '8,65 tỷ', '5,64 tỷ', '7,55 tỷ',
       '11,99 tỷ', '8,25 tỷ', '3,04 tỷ', '17,9 tỷ', '5,3 tỷ', '5,6 tỷ',
       '5,25 tỷ', '5,4 tỷ', '14,999 tỷ', '7,48 tỷ', '6,97 tỷ', '4,84 tỷ',
       '9 tỷ', '1,979 tỷ', '4,6 tỷ', '32,999 tỷ', '33,5 tỷ', '8,6 tỷ',
       '6,79 tỷ', '7,36 tỷ', '6,886 tỷ', '17,5 tỷ', '12,18 tỷ', '17,3 tỷ',
       '24,9 tỷ', '22,9 tỷ', '9,7 tỷ', '12,99 tỷ', '10,7 tỷ', '6,15 tỷ',
       '6,09 tỷ', '40,5 tỷ', '19,95 tỷ', '23,5 tỷ', '8,899 tỷ', '5,67 tỷ',
       '6,7 tỷ', '15,799 tỷ', '1,95 tỷ', '2,3 tỷ', '14,2 tỷ', '3,979 tỷ',
       '56 tỷ', '13,99 tỷ', '1,3 tỷ', '8,1 tỷ', '19,1 tỷ', '6,3 tỷ',
       '6,1 tỷ', '6,98 tỷ', '4,25 tỷ', '36 tỷ', '4,3 tỷ', '14,9 tỷ',
       '19 tỷ', '275 tỷ', '112 tỷ', '17,95 tỷ', '5,38 tỷ', '10,999 tỷ',
       '28,5 tỷ', '8,86 tỷ', '2,99 tỷ', '17,99 tỷ', '37 tỷ', '2,6 tỷ',
       '4,789 tỷ', '15,6 tỷ', '26,5 tỷ', '4,9 tỷ', '3 tỷ', '49 tỷ',
       '24 tỷ', '6,68 tỷ', '2,98 tỷ', '6,45 tỷ', '5,55 tỷ', '3,6 tỷ',
       '2,8 tỷ', '1,59 tỷ', '1,98 tỷ', '3,45 tỷ', '2 tỷ', '10,6 tỷ',
       '7,68 tỷ', '2,38 tỷ', '14,99 tỷ', '8,99 tỷ', '820 triệu',
       '9,87 tỷ', '6,75 tỷ', '5,939 tỷ', '1,25 tỷ', '1,18 tỷ', '6,58 tỷ',
       '4,15 tỷ', '11,7 tỷ', '11,1 tỷ', '7,1 tỷ', '21,8 tỷ', '13,3 tỷ',
       '12,2 tỷ', '15,8 tỷ', '3,15 tỷ', '4,33 tỷ', '1,8 tỷ', '22,4 tỷ',
       '22,8 tỷ', '9,39 tỷ', '6,686 tỷ', '3,5 tỷ', '12,3 tỷ', '13,499 tỷ',
       '11,4 tỷ', '25,99 tỷ', '31,9 tỷ', '23,999 tỷ', '15,99 tỷ',
       '1,6 tỷ', '4,34 tỷ', '4,65 tỷ', '4,1 tỷ', '5,69 tỷ', '4,99 tỷ',
       '2,48 tỷ', '4,48 tỷ', '4,39 tỷ', '17 tỷ', '13,2 tỷ', '23,99 tỷ',
       '5,48 tỷ', '10,3 tỷ', '3,28 tỷ', '18,75 tỷ', '79 tỷ', '5,29 tỷ',
       '9,65 tỷ', '3,25 tỷ', '35 tỷ', '22,49 tỷ', '3,1 tỷ', '1,79 tỷ',
       '33 tỷ', '15,2 tỷ', '5,28 tỷ', '28 tỷ', '4,4 tỷ', '5,52 tỷ',
       '17,1 tỷ', '3,83 tỷ', '5,15 tỷ', '2,1 tỷ', '35,5 tỷ', '12,89 tỷ',
       '21 tỷ', '2,08 tỷ', '33,8 tỷ', '5,94 tỷ', '3,19 tỷ', '27,5 tỷ',
       '6,88 tỷ', '3,75 tỷ', '5,36 tỷ', '10,4 tỷ', '7,49 tỷ', '4,96 tỷ',
       '4,89 tỷ', '14,7 tỷ', '2,79 tỷ', '4,77 tỷ', '10,35 tỷ', '18,8 tỷ',
       '1,58 tỷ', '4,97 tỷ', '10,45 tỷ', '14,95 tỷ', '17,2 tỷ', '2,49 tỷ',
       '5,87 tỷ', '3,4 tỷ', '4,235 tỷ', '20,5 tỷ', '13,1 tỷ', '19,9 tỷ',
       '10,25 tỷ', '42,5 tỷ', '14,1 tỷ', '9,45 tỷ', '11,01 tỷ', '20,6 tỷ',
       '19,3 tỷ', '1,69 tỷ', '6,28 tỷ', '9,85 tỷ', '86 tỷ', '4,66 tỷ',
       '22,999 tỷ', '18,6 tỷ', '6,78 tỷ', '8,54 tỷ', '7,78 tỷ', '3,79 tỷ',
       '2,44 tỷ', '2,59 tỷ', '7,28 tỷ', '15,45 tỷ', '7,39 tỷ',
       '13,999 tỷ', '4,125 tỷ', '5,96 tỷ', '7,948 tỷ', '27 tỷ',
       '11,79 tỷ', '21,5 tỷ', '19,99 tỷ', '20,2 tỷ', '39,9 tỷ', '42 tỷ',
       '6,149 tỷ', '8,55 tỷ', '7,779 tỷ', '9,75 tỷ', '4,78 tỷ', '7,66 tỷ',
       '31 tỷ', '4,28 tỷ', '1,45 tỷ', '15,46 tỷ', '40 tỷ', '25,5 tỷ',
       '5,379 tỷ', '8,35 tỷ', '24,8 tỷ', '8,49 tỷ', '6,55 tỷ',
       '12,999 tỷ', '4,888 tỷ', '6,075 tỷ', '2,17 tỷ', '2,78 tỷ',
       '3,88 tỷ', '3,12 tỷ', '4,88 tỷ', '4,09 tỷ', '6,59 tỷ', '5,56 tỷ',
       '2,68 tỷ', '2,74 tỷ', '5,97 tỷ', '9,68 tỷ', '9,1 tỷ', '5,05 tỷ',
       '2,5 tỷ', '8,88 tỷ', '106 tỷ', '32 tỷ', '6,38 tỷ', '92 tỷ',
       '19,2 tỷ', '14,3 tỷ', '4,67 tỷ', '2,73 tỷ', '36,5 tỷ', '2,54 tỷ',
       '4,49 tỷ', '4,969 tỷ', '4,19 tỷ', '6,225 tỷ', '9,98 tỷ',
       '7,799 tỷ', '4,07 tỷ', '10,46 tỷ', '10,98 tỷ', '14,4 tỷ',
       '3,499 tỷ', '6,889 tỷ', '5,555 tỷ', '34 tỷ', '25,9 tỷ', '3,299 tỷ',
       '5,86 tỷ', '4,18 tỷ', '20,8 tỷ', '1,5 tỷ', '12,57 tỷ', '8,38 tỷ',
       '9,35 tỷ', '4,199 tỷ', '9,28 tỷ', '3,38 tỷ', '23,9 tỷ', '2,05 tỷ',
       '2,94 tỷ', '20,7 tỷ', '6,57 tỷ', '7,02 tỷ', '6,29 tỷ', '3,14 tỷ',
       '21,2 tỷ', '8,19 tỷ', '18,45 tỷ', '13,75 tỷ', '7,05 tỷ', '38 tỷ',
       '6,56 tỷ', '7,72 tỷ', '8,799 tỷ', '2,86 tỷ', '1,99 tỷ', '3,3 tỷ',
       '3,39 tỷ', '5,299 tỷ', '16,6 tỷ', '8,29 tỷ', '15,7 tỷ', '6,13 tỷ',
       '3,48 tỷ', '38,5 tỷ', '30,5 tỷ', '3,78 tỷ', '10,79 tỷ', '2,65 tỷ',
       '6,53 tỷ', '5,588 tỷ', '7,93 tỷ', '10,85 tỷ', '7,885 tỷ',
       '7,35 tỷ', '6,94 tỷ', '14,35 tỷ', '3,86 tỷ', '4,69 tỷ', '3,66 tỷ',
       '8,98 tỷ', '7,18 tỷ', '11,699 tỷ', '5,26 tỷ', '6,899 tỷ',
       '5,09 tỷ', '8,688 tỷ', '11,68 tỷ', '1,1 tỷ', '9,999 tỷ',
       '3,567 tỷ', '3,23 tỷ', '8,68 tỷ', '8,85 tỷ', '350 tỷ', '1,42 tỷ',
       '18,3 tỷ', '3,868 tỷ', '11,999 tỷ', '10,95 tỷ', '9,15 tỷ',
       '13,68 tỷ', '12,1 tỷ', '7,46 tỷ', '4,87 tỷ', '102 tỷ', '52 tỷ',
       '12,79 tỷ', '6,67 tỷ', '3,44 tỷ', '18,7 tỷ', '24,3 tỷ', '8,09 tỷ',
       '4,799 tỷ', '8,498 tỷ', '7,699 tỷ', '7,999 tỷ', '5,986 tỷ',
       '3,49 tỷ', '18,9 tỷ', '6,449 tỷ', '5,43 tỷ', '2,97 tỷ', '6,579 tỷ',
       '7,435 tỷ', '4,46 tỷ', '890 triệu', '23,1 tỷ', '3,368 tỷ',
       '8,15 tỷ', '2,69 tỷ', '8,59 tỷ', '2,18 tỷ', '8,643 tỷ', '5,37 tỷ',
       '2,92 tỷ', '4,845 tỷ', '3,29 tỷ', '4,08 tỷ', '10,18 tỷ', '5,24 tỷ',
       '7,986 tỷ', '6,999 tỷ', '8,78 tỷ', '12,35 tỷ', '8,05 tỷ', '58 tỷ',
       '4,699 tỷ', '3,57 tỷ', '4,788 tỷ', '500 triệu', '3,26 tỷ',
       '5,54 tỷ', '9,286 tỷ', '36,9 tỷ', '4,999 tỷ', '2,699 tỷ',
       '7,29 tỷ', '6,87 tỷ', '4,685 tỷ', '1,299 tỷ', '6,18 tỷ', '6,32 tỷ',
       '3,87 tỷ', '5,785 tỷ', '75 tỷ', '7,58 tỷ', '4,29 tỷ', '4,868 tỷ',
       '3,58 tỷ', '3,54 tỷ', '13,49 tỷ', '7,38 tỷ', '700 triệu',
       '21,3 tỷ', '1,88 tỷ', '4,57 tỷ', '5,945 tỷ', '968 triệu',
       '43,5 tỷ', '14,6 tỷ', '8,28 tỷ', '16,2 tỷ', '57,9 tỷ', '6,799 tỷ',
       '4,899 tỷ', '142 tỷ', '3,586 tỷ', '4,268 tỷ', '8,58 tỷ',
       '4,271 tỷ', '4,399 tỷ', '5,199 tỷ', '4,47 tỷ', '5,93 tỷ',
       '3,56 tỷ', '4,568 tỷ', '5,76 tỷ', '12,98 tỷ', '3,59 tỷ', '8,96 tỷ',
       '3,789 tỷ', '3,486 tỷ', '4,939 tỷ', '10,69 tỷ', '5,698 tỷ',
       '6,789 tỷ', '34,5 tỷ', '8,199 tỷ', '5,33 tỷ', '16,7 tỷ', '1,78 tỷ',
       '4,63 tỷ', '3,639 tỷ', '3,139 tỷ', '8,97 tỷ', '7,439 tỷ',
       '5,59 tỷ', '21,7 tỷ', '3,699 tỷ', '2,968 tỷ', '2,06 tỷ',
       '12,25 tỷ', '11,75 tỷ', '5,699 tỷ', '4,299 tỷ', '7,399 tỷ',
       '7,56 tỷ', '5,82 tỷ', '1 tỷ', '17,6 tỷ', '2,33 tỷ', '3,056 tỷ',
       '4,05 tỷ', '6,63 tỷ', '10,83 tỷ', '4,56 tỷ', '5,889 tỷ', '9,69 tỷ',
       '8,18 tỷ', '5,32 tỷ', '5,568 tỷ', '2,87 tỷ', '26,8 tỷ', '8,16 tỷ',
       '3,67 tỷ', '12,568 tỷ', '7,899 tỷ', '9,268 tỷ', '8,39 tỷ',
       '2,88 tỷ', '16,789 tỷ', '6,62 tỷ', '3,97 tỷ', '4,93 tỷ', '12,7 tỷ',
       '6,199 tỷ', '6,64 tỷ', '16,666 tỷ', '9,25 tỷ', '5,486 tỷ',
       '15,15 tỷ', '8,385 tỷ', '70 tỷ', '7,47 tỷ', '2,399 tỷ', '4,76 tỷ',
       '6,37 tỷ', '2,499 tỷ', '1,86 tỷ', '8,456 tỷ', '2,15 tỷ',
       '15,75 tỷ', '12,4 tỷ', '29,5 tỷ', '15,89 tỷ', '5,92 tỷ',
       '20,999 tỷ', '9,299 tỷ', '7,97 tỷ', '11,69 tỷ', '9,78 tỷ',
       '21,99 tỷ', '10,149 tỷ', '11,49 tỷ', '10,15 tỷ', '46 tỷ',
       '11,95 tỷ', '29,999 tỷ', '15,79 tỷ', '16,95 tỷ', '12,39 tỷ',
       '8,74 tỷ', '8,48 tỷ', '13,568 tỷ', '6,875 tỷ', '222 tỷ', '9,48 tỷ',
       '29,4 tỷ', '9,55 tỷ', '10,59 tỷ', '36,6 tỷ', '1,76 tỷ', '55 tỷ',
       '9,397 tỷ', '13,45 tỷ', '13,7 tỷ', '4,16 tỷ', '15,3 tỷ', '7,83 tỷ',
       '4,92 tỷ', '11,85 tỷ', '13,56 tỷ', '11,19 tỷ', '1,97 tỷ',
       '8,399 tỷ', '3,84 tỷ', '15,1 tỷ', '7,679 tỷ', '13,55 tỷ',
       '41,5 tỷ', '9,868 tỷ', '7,485 tỷ', '17,8 tỷ', '10,89 tỷ',
       '20,9 tỷ', '5,31 tỷ', '28,9 tỷ', '12,85 tỷ', '1,4 tỷ'],
      dtype=object)

In [31]:
def transform_gia_ban(value):
    if pd.isnull(value):
        return value
    if isinstance(value, str):
        if "tỷ" in value:
            value = value.replace("tỷ", "").replace(",", ".").strip()
            try:
                return float(value)
            except ValueError:
                return np.nan
        elif "triệu" in value:
            value = value.replace("triệu", "").replace(",", ".").strip()
            try:
                return float(value) / 1000  # Chuyển triệu sang tỷ
            except ValueError:
                return np.nan
    return value

df['gia_ban'] = df['gia_ban'].apply(transform_gia_ban)

In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7961 entries, 0 to 8272
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   giay_to_phap_ly  7961 non-null   object
 1   dien_tich        7961 non-null   float64
 2   gia_ban          7961 non-null   float64
 3   loai_hinh        7961 non-null   object
 4   so_phong_ngu     7961 non-null   object
 5   mo_ta            7961 non-null   object
 6   tieu_de          7961 non-null   object
 7   dia_chi          7961 non-null   object
 8   bieu_do_gia      7961 non-null   object
dtypes: float64(2), object(7)
memory usage: 622.0+ KB

### Nhận xét
Cột  đã được chuyển từ dạng text sang **float64** (đơn vị: tỷ VNĐ). Logic chuyển đổi:
- "X tỷ" → X (float)
- "X triệu" → X / 1000 (quy về tỷ)
- Giá trị không parse được → NaN

## 5. Chuyển đổi cột  sang numeric

In [33]:
df["so_phong_ngu"].unique()

array(['2 phòng', '4 phòng', '3 phòng', '5 phòng', '9 phòng', '6 phòng',
       'nhiều hơn 10 phòng', '7 phòng', '1 phòng', '10 phòng', '8 phòng'],
      dtype=object)

In [34]:
def transform_so_phong_ngu(value):
    if pd.isnull(value):
        return value
    if isinstance(value, str):
        if value.lower() in ["nhiều hơn 10 phòng"]:
            return 11  # Giả sử "nhiều hơn 10 phòng" là 11
        value = value.replace("phòng", "").strip()
        try:
            return int(value)
        except ValueError:
            return np.nan
    return value

df['so_phong_ngu'] = df['so_phong_ngu'].apply(transform_so_phong_ngu)

In [35]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7961 entries, 0 to 8272
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   giay_to_phap_ly  7961 non-null   object
 1   dien_tich        7961 non-null   float64
 2   gia_ban          7961 non-null   float64
 3   loai_hinh        7961 non-null   object
 4   so_phong_ngu     7961 non-null   int64
 5   mo_ta            7961 non-null   object
 6   tieu_de          7961 non-null   object
 7   dia_chi          7961 non-null   object
 8   bieu_do_gia      7961 non-null   object
dtypes: float64(2), int64(1), object(6)
memory usage: 622.0+ KB

### Nhận xét
Cột  đã được chuyển sang **int64**. Xử lý đặc biệt:
- "X phòng" → X (int)
- "nhiều hơn 10 phòng" → 11 (giả định hợp lý, chỉ chiếm rất ít bản ghi)
- Giá trị không parse được → NaN

In [36]:
df.shape

(7961, 9)

## 6. Lưu dataset đã clean

In [37]:
df.to_csv("../data/processed/dataset_cleaned.csv", index=False, encoding="utf-8-sig")

In [38]:
%pip install pyarrow

Requirement already satisfied: pyarrow in c:\users\lenovo\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (23.0.1)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.0 -> 26.0.1
[notice] To update, run: C:\Users\Lenovo\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

In [39]:
df.to_parquet("../data/processed/dataset_cleaned.parquet", engine="pyarrow", index=False)

In [40]:
import os
os.listdir("../data/processed/")

['dataset_cleaned.csv',
 'dataset_cleaned.parquet',
 'dataset_merged.csv',
 'data_modeling.csv',
 'data_modeling.parquet',
 'pyspark_predictions.parquet']

In [41]:
test_df = pd.read_csv("../data/processed/dataset_cleaned.csv", encoding="utf-8-sig")

In [42]:
test_df.shape

(7961, 9)

In [43]:
test_df = pd.read_parquet("../data/processed/dataset_cleaned.parquet", engine="pyarrow")

In [44]:
test_df.shape

(7961, 9)

## Kết luận

### Tổng kết quá trình Data Cleaning

| Bước | Mô tả | Trước | Sau |
|------|-------|-------|-----|
| Load data | Dataset thô từ notebook 01 | 8,273 x 24 | - |
| Chọn cột | Giữ 9 cột quan trọng, bỏ 15 cột dư thừa | 24 cột | 9 cột |
| Xóa dòng rỗng | Loại bỏ dòng thiếu toàn bộ thông tin | 8,273 dòng | 7,961 dòng |
| Clean  | Lowercase + fill NaN = "chưa xác định" | 501 NaN | 0 NaN |
| Clean  | Text → float (m²) | object | float64 |
| Clean  | Text → float (tỷ VNĐ) | object | float64 |
| Clean  | Text → int | object | int64 |

### Dataset sau cleaning
- **Số dòng**: 7,961 (giảm 312 dòng, ~3.8%)
- **Số cột**: 9
- **Không còn missing values** ở các cột quan trọng
- **Kiểu dữ liệu** đã chuẩn hóa: 2 float, 1 int, 6 object

### Các cột đã bỏ và lý do
- , : >99% missing
- : >84% missing
- : >52% missing, không liên quan đến giá
- , , : >33% missing
- , : ~26-28% missing, thông tin đã có trong 
- , , , : trùng lặp hoặc dẫn xuất từ các cột khác
- : chỉ dùng cho truy vết, không cần cho modeling

### File output
-  (CSV, UTF-8-sig)
-  (Parquet, PyArrow)

### Bước tiếp theo
→ Notebook : Trích xuất thêm features từ text (tiêu đề, mô tả, địa chỉ) và biểu đồ giá khu vực.